### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by Athiiii** [rgwch/elexis-oob#31]
I get following error message when running `docker-compose up -d`:
Apparently some packages are outdated.
------
 > [build-stage 3/3] RUN apt-get update   && apt-get install -y git   && git clone -b ungrad2023 https://github.com/rgwch/elexis-3-core   && git clone -b ungrad2023 https://github.com/rgwch/elexis-3-base   && git clone -b ungrad2023 https://github.com/rgwch/elexis-ungrad   && export MAVEN_OPTS="-Xmx1024m"   && cd elexis-3-core   && mvn verify -Dtycho.localArtifacts=ignore -Dmaven.test.skip=true -P all-archs   && cd ../elexis-3-base   && mvn verify -Dtycho.localArtifacts=ignore -Dmaven.test.skip=true -Delexis_root=/opt   && cd ../elexis-ungrad   && mvn verify -Delexis_root=/opt:
#0 0.658 Ign:1 http://deb.debian.org/debian stretch InRelease
#0 0.668 Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
#0 0.689 Ign:3 http://deb.debian.org/debian stretch-updates InRelease
#0 0.701 Ign:4 http://deb.debian.org/debian stretch Release
#0 0.701 Ign:5 http://security.debian.org/debian-security stretch/updates Release
#0 0.713 Ign:6 http://deb.debian.org/debian stretch-updates Release
#0 0.715 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 0.725 Ign:8 http://deb.debian.org/debian stretch/main all Packages
#0 0.728 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 0.736 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#0 0.742 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 0.748 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 0.759 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#0 0.770 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 0.771 Ign:8 http://deb.debian.org/debian stretch/main all Packages
#0 0.783 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#0 0.783 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 0.796 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 0.796 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 0.808 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#0 0.810 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 0.820 Ign:8 http://deb.debian.org/debian stretch/main all Packages
#0 0.824 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 0.831 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#0 0.839 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 0.853 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 0.853 Ign:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 0.865 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#0 0.866 Ign:7 http://security.debian.org/debian-security stretch/updates/main all Packages
#0 0.876 Ign:8 http://deb.debian.org/debian stretch/main all Packages
#0 0.879 Err:9 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#0 0.879   404  Not Found [IP: 151.101.194.132 80]
#0 0.888 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#0 0.907 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 0.919 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#0 0.932 Ign:8 http://deb.debian.org/debian stretch/main all Packages
#0 0.943 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#0 0.955 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 0.967 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#0 0.978 Ign:8 http://deb.debian.org/debian stretch/main all Packages
#0 0.991 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
#0 0.991   404  Not Found
#0 1.003 Err:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#0 1.003   404  Not Found
#0 1.014 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#0 1.018 Reading package lists...
#0 1.025 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#0 1.025 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#0 1.025 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#0 1.025 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#0 1.025 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
#0 1.025 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#0 1.025 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: executor failed running [/bin/sh -c apt-get update   && apt-get install -y git   && git clone -b ${BRANCH} https://github.com/rgwch/elexis-3-core   && git clone -b ${BRANCH} https://github.com/rgwch/elexis-3-base   && git clone -b ${BRANCH} https://github.com/rgwch/elexis-ungrad   && export MAVEN_OPTS="-Xmx1024m"   && cd elexis-3-core   && mvn verify -Dtycho.localArtifacts=ignore -Dmaven.test.skip=true -P all-archs   && cd ../elexis-3-base   && mvn verify -Dtycho.localArtifacts=ignore -Dmaven.test.skip=true -Delexis_root=/opt   && cd ../elexis-ungrad   && mvn verify -Delexis_root=/opt]: exit code: 100

**Comment by gortmanns** [comment]
That´s correct. It appears the included maven version 3.6.0 is no longer available or supported in the current linux releases.

Workaround:
after the git clone command, has successfully completed, edit the file
`elexis-oob/appserver/Dockerfile`

The very first line reads:
`FROM maven:3.6.0-jdk-8-slim as build-stage`
change this to
`FROM maven:3.8.6-jdk-8-slim as build-stage`

At least this version is not too old to not be found in the repositories (I tried with Ubuntu Server 22.04.4)

After you that change, you can continue normally and the docker container will be created successfully and the only error message is one from the PACS system not being able to connect to a port. Did not affect me being able get to the start webpage though by entering 
`Your-Servers-IP:3000` 
into your webbrowser.

But then I encountered another error which I was not able to resolve:

When trying to initialise the database, I got a 
`ERRor: getaddrinfo EAI_AGAIN elexisdb`
message and the database was not initiated.
It appears this error is somehow related to the newer docker versions (as far as I found out versions after 16.2) handle networking in a different way and inside the container the DNS does not work anymore.
I have not found a way around this yet unfortunately.

**Comment by rgwch** [comment]
Updated some dependencies. Should work now. Tested with Docker 24.0.5 and compose 1.29.2

**Comment by gortmanns** [comment]
docker-compose now runs all the way through without issues.

I can then find the management website under

http://My-Server-IP:3000  No issues so far.

But when I try to initialise the database, I get the following error

`could not connect
Error: getaddrinfo ENOTFOUND elexisdb
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
    --------------------
    at Protocol._enqueue (/home/node/site/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/node/site/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/node/site/node_modules/mysql/lib/Connection.js:116:18)
    at /home/node/site/routes/db.js:44:8
    at Layer.handle [as handle_request] (/home/node/site/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/node/site/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/home/node/site/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/home/node/site/node_modules/express/lib/router/layer.js:95:5)
    at /home/node/site/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/node/site/node_modules/express/lib/router/index.js:346:12)`

To me this looks like something went wrong about how the database is accessed.
Maybe an issue with traffic routing between the actual physical machine and the docker container?

`ifconfig`
on the main machine returns a whole lot of interfaces. Many only IPv6.
Apart from the main interface eth0, I have found 3 more that use IPv4 which seem to be somehow docker-related:

Two starting with 
`br-xxxxxxxxxxxx ` with IPv4 addresses 172.18.0.1 and 172.19.0.1 respectively.
I assume those are bridge interfaces

and a third named 
`docker0` with IPv4 address 172.17.0.1
